Fixing & improving example
applitools/eyes-selenium-typescript-hello-world pull request #2
Opened 2019-06-22 11:18 UTC by fescobar

2019-06-22 11:20 UTC, fescobar commented
@danielputerman can you accept my PR? Thank you.

2019-07-12 12:23 UTC, danielputerman requested changes

2019-07-12 12:23 UTC, danielputerman commented on package.json
> +    "@types/selenium-webdriver": "^3.0.16",
This is a downgrade of the Selenium version used, which is probably an unwanted change. Please update the request to use the latest one.

2019-07-12 12:23 UTC, danielputerman commented on package.json
> +    "@types/selenium-webdriver": "^3.0.16",
(latest one of 3.x that is)

2019-07-12 12:23 UTC, danielputerman commented on src/EyesWebExample.ts
> +    eyes.setApiKey('PUT_YOUR_API_KEY')
Actually, there's no real need to set the API explicitly, just set it in the APPLITOOLS_API_KEY env variable, and it will be automatically picked up. You can change this to a comment, and it'll be fine.

2019-07-12 12:24 UTC, danielputerman commented
Thanks for the PR @fescobar ! Some minor changes are needed. Once you update, I'll merge the PR

2019-07-13 09:27 UTC, fescobar commented on package.json
> +    "@types/selenium-webdriver": "^3.0.16",
The latest `selenium-webdriver` is ALPHA `4.0.0-alpha.4`. It's not totally final. 
And the types are not supporting that version
```
    "@types/selenium-webdriver": "^4.0.1",
    "selenium-webdriver": "^4.0.0-alpha.4",
```

```
node_modules/eyes.selenium/typings/index.d.ts:464:47 - error TS2694: Namespace '"/Users/frank.escobar/Documents/git/eyes-selenium-typescript-hello-world/node_modules/@types/selenium-webdriver/lib/promise".promise' has no exported member 'Promise'.

464     findElements(locator: By|object): promise.Promise<EyesRemoteWebElement[]>;
```

2019-07-13 13:41 UTC, danielputerman commented on package.json
> +    "@types/selenium-webdriver": "^3.0.16",
Yes, I made an additional comment right after that: "latest of 3.x" :) 
So, basically 3.6.0 (https://www.npmjs.com/package/selenium-webdriver/v/3.6.0)

2019-07-13 14:07 UTC, fescobar commented on package.json
> +    "@types/selenium-webdriver": "^3.0.16",
@danielputerman done

2019-07-13 14:26 UTC, danielputerman commented on package.json
> +    "@types/selenium-webdriver": "^3.0.16",
👍

2019-07-13 21:12 UTC, merged